### ISSUE TITLE
Website Redesign 

### ISSUE THREAD

**Issue by RobDavis** [CodeForFtL/project-ideas#2]
## Short description of the idea (140 character tweet):

Updated Code for FTL website based on Code for Miami's design. 

## What is your project concept or idea? What challenge or opportunity will it solve?

Spread awareness for our team! Or should we change to https://github.com/brigadehub/brigadehub/

### Do you have photos of them? Or quotes?

_Your answer_

## Issue area(s) relevant to your project idea:

- Other (marketing)

## What is the current state of your project idea?

- I have an idea or **concept** of a solution, but have not yet prototyped or tested it

### Do you have any links to news articles, text, mockups, code, or data?

V1 here: https://protomikex.github.io/code-for-ftl.github.io/
Code: https://github.com/protomikex/code-for-ftl.github.io

### Are you representing a group in submitting this project idea? 

Forked from Code for Miami via Mike

**Comment by RobDavis** [comment]
I'm thinking of trying out brigadehub: https://github.com/brigadehub/brigadehub/

**Comment by hchev001** [comment]
So after some digging through brigadehub, I realized the project has been abandoned. Is the website redesign something you still want @RobDavis ? Aesthetically the current codeforftl.org is pleasant, so I'm guessing you want some features that the brigadehub provided? Or still pursue the redesign of the website and include web application features?

**Comment by ryanvgates** [comment]
@hchev001 I just checked back up on brigadehub and it looks like the project is being retired. I still like the idea behind it, that we focus on our community needs and projects rather than the site itself. I'm not sure exactly what our next step should be. Going back to the basic premise of the site, I think it needs the following.

1. Provide onboarding for new/interested people
2. Show our current projects and their status (or a path to get that info)
3. Show our story/previous projects and wins

@RobDavis @qtrandev thoughts?
